// Demo quiz bank + generator. Each topic has 5 MCQs + 2 short-answer (SA)
// questions. In production, these are generated by Gemini grounded on
// textbook chunks; in demo mode we serve curated questions from the
// BSE Odisha Class 9 textbook exercises.

import type { DemoTopic } from "@/lib/curriculum/bse-class9";
import { findTopic } from "@/lib/curriculum/bse-class9";

export type MCQ = {
  q: string;
  options: string[];
  correct: number; // 0-based index
  explanation: string;
};
export type ShortQ = {
  q: string;
  modelAnswer: string;
  keywords: string[];
};

export type Quiz = {
  topicId: string;
  difficulty: "practice" | "master";
  mcqs: MCQ[];
  shortQs: ShortQ[];
};

const QUIZ_BANK: Record<string, Quiz> = {
  "mth-1-1:practice": {
    topicId: "mth-1-1",
    difficulty: "practice",
    mcqs: [
      {
        q: "ଯଦି S = {1, 2, 3, 4, 5} ତେବେ କେଉଁଟି ସତ୍ୟ?",
        options: ["3 ∉ S", "6 ∈ S", "3 ∈ S", "S ଅସୀମ"],
        correct: 2,
        explanation: "3 ତାଲିକାରେ ଥିବାରୁ 3 ∈ S।",
      },
      {
        q: "{x : x ଏକ ସ୍ୱାଭାବିକ ସଂଖ୍ୟା ଏବଂ 1 ≤ x ≤ 4} ର ତାଲିକା ରୂପ?",
        options: ["{1,2,3}", "{2,3,4}", "{1,2,3,4}", "{0,1,2,3,4}"],
        correct: 2,
        explanation: "1, 2, 3, 4 ସମସ୍ତ ଯୋଗ୍ୟ।",
      },
      {
        q: "ଶୂନ୍ୟ ସେଟ୍ କୁ କ'ଣ ସୂଚିତ କରାଯାଏ?",
        options: ["{0}", "φ", "N", "{φ}"],
        correct: 1,
        explanation: "ଶୂନ୍ୟ ସେଟ୍ ର ସଂକେତ φ ବା { }।",
      },
      {
        q: "ଯଦି A = {a, b} ତେବେ A ର ଉପସେଟ୍ ସଂଖ୍ୟା?",
        options: ["2", "3", "4", "5"],
        correct: 2,
        explanation: "2² = 4 (φ, {a}, {b}, {a,b})।",
      },
      {
        q: "କେଉଁଟି ସସୀମ ସେଟ୍ ନୁହେଁ?",
        options: [
          "{1, 2, 3}",
          "φ",
          "{x : x ଏକ ସ୍ୱାଭାବିକ ସଂଖ୍ୟା}",
          "{a, b, c, d}",
        ],
        correct: 2,
        explanation: "ସ୍ୱାଭାବିକ ସଂଖ୍ୟା ଗଣ ଅସୀମ।",
      },
    ],
    shortQs: [
      {
        q: "ତୁମର ଶ୍ରେଣୀଗୃହର ୫ ଜଣ ବନ୍ଧୁଙ୍କୁ ନେଇ ଏକ ସେଟ୍ ଗଠନ କର।",
        modelAnswer:
          "F = { ସୀତା, ରାମ, ରାଧା, କୃଷ୍ଣ, ଲକ୍ଷ୍ମଣ } — ଏଠାରେ |F| = 5।",
        keywords: ["ସେଟ୍", "ଉପାଦାନ", "ତାଲିକା"],
      },
      {
        q: "ସେଟ୍ ର ସଂଜ୍ଞା ଲେଖ ଏବଂ ଏକ ଉଦାହରଣ ଦିଅ।",
        modelAnswer:
          "ସେଟ୍ ହେଉଛି କେତେକ ନିର୍ଦ୍ଦିଷ୍ଟ ବସ୍ତୁର ସମାବେଶ। ଉଦାହରଣ: A = {2, 4, 6, 8}।",
        keywords: ["ସଂଜ୍ଞା", "ନିର୍ଦ୍ଦିଷ୍ଟ", "ସମାବେଶ"],
      },
    ],
  },

  "mth-2-1:practice": {
    topicId: "mth-2-1",
    difficulty: "practice",
    mcqs: [
      {
        q: "କେଉଁଟି ଏକ ପରିମେୟ ସଂଖ୍ୟା?",
        options: ["√2", "π", "3/7", "0.1010010001..."],
        correct: 2,
        explanation: "3/7 ହେଉଛି p/q ରୂପରେ ଲେଖିହୁଏ।",
      },
      {
        q: "N, Z, Q ମଧ୍ୟରେ କେଉଁଟି ସତ୍ୟ?",
        options: ["Q ⊂ Z ⊂ N", "N ⊂ Z ⊂ Q", "Z ⊂ N ⊂ Q", "Q ⊂ N"],
        correct: 1,
        explanation: "ପ୍ରତ୍ୟେକ ସ୍ୱାଭାବିକ → ପୂର୍ଣ୍ଣ → ପରିମେୟ।",
      },
      {
        q: "0 କେଉଁ ସେଟ୍ ରେ ନାହିଁ?",
        options: ["N", "W", "Z", "Q"],
        correct: 0,
        explanation: "N = {1, 2, ...}, 0 ଏଥିରେ ନାହିଁ।",
      },
      {
        q: "0.75 କୁ ଭଗ୍ନରୂପରେ ଲେଖ।",
        options: ["75/10", "3/4", "7/5", "4/3"],
        correct: 1,
        explanation: "0.75 = 75/100 = 3/4।",
      },
      {
        q: "−3 କେଉଁଠି ନାହିଁ?",
        options: ["Z", "Q", "R", "N"],
        correct: 3,
        explanation: "ଋଣାତ୍ମକ ସଂଖ୍ୟା N ରେ ନାହିଁ।",
      },
    ],
    shortQs: [
      {
        q: "7/3 ଏବଂ 11/2 ମଧ୍ୟରେ ଏକ ପରିମେୟ ସଂଖ୍ୟା ନିର୍ଣ୍ଣୟ କର।",
        modelAnswer:
          "ହରକୁ ସମାନ କର: 14/6 ଓ 33/6; ଏ ଦୁଇ ମଧ୍ୟରେ 20/6 = 10/3 ଏକ ପରିମେୟ ସଂଖ୍ୟା।",
        keywords: ["ହର", "ସମାନ", "ମଧ୍ୟ"],
      },
      {
        q: "କହ: 'ପ୍ରତ୍ୟେକ ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା ଏକ ପରିମେୟ' — ସତ୍ୟ ନା ଅସତ୍ୟ? କାରଣ ଦିଅ।",
        modelAnswer:
          "ସତ୍ୟ। କାରଣ ଯେକୌଣସି ପୂର୍ଣ୍ଣ ସଂଖ୍ୟା n କୁ n/1 ଆକାରରେ ଲେଖିହୁଏ।",
        keywords: ["ସତ୍ୟ", "n/1", "ପରିମେୟ"],
      },
    ],
  },

  "mth-2-2:practice": {
    topicId: "mth-2-2",
    difficulty: "practice",
    mcqs: [
      {
        q: "କେଉଁଟି ଏକ ଅପରିମେୟ ସଂଖ୍ୟା?",
        options: ["22/7", "0.333...", "√3", "−5"],
        correct: 2,
        explanation: "√3 ନିଶ୍ଚୟ ଅପରିମେୟ; 22/7 ପରିମେୟ।",
      },
      {
        q: "π ର ଆସନ୍ନ ମୂଲ୍ୟ ?",
        options: ["22/7", "3.14", "ଉଭୟ (a) ଓ (b)", "କୌଣସି ନୁହେଁ"],
        correct: 2,
        explanation: "22/7 ଓ 3.14 ଉଭୟ π ର ଆସନ୍ନ ମୂଲ୍ୟ।",
      },
      {
        q: "√2 ର ଦଶମିକ ରୂପ?",
        options: [
          "ସମାପ୍ତ",
          "ପୌନଃପୁନିକ",
          "ଅସମାପ୍ତ ଓ ଅପୌନଃପୁନିକ",
          "ଶୂନ୍ୟ",
        ],
        correct: 2,
        explanation: "ଅପରିମେୟର ଦଶମିକ ଅସମାପ୍ତ ଓ ଅପୌନଃପୁନିକ।",
      },
      {
        q: "ଦୁଇଟି ଅପରିମେୟର ଯୋଗଫଳ ସର୍ବଦା ?",
        options: ["ପରିମେୟ", "ଅପରିମେୟ", "ପରିମେୟ ବା ଅପରିମେୟ", "ଶୂନ୍ୟ"],
        correct: 2,
        explanation: "ଉଦା. √2 + (−√2) = 0 (ପରିମେୟ)।",
      },
      {
        q: "3 + √2 ?",
        options: ["ପରିମେୟ", "ଅପରିମେୟ", "ସ୍ୱାଭାବିକ", "ଶୂନ୍ୟ"],
        correct: 1,
        explanation: "ପରିମେୟ + ଅପରିମେୟ = ଅପରିମେୟ।",
      },
    ],
    shortQs: [
      {
        q: "√2 ଅପରିମେୟ — ସଂକ୍ଷିପ୍ତ ପ୍ରମାଣ ଦିଅ।",
        modelAnswer:
          "√2 = p/q (ସାଧାରଣ ଗୁଣନୀୟକ 1) ମାନିଲେ 2q² = p²। ତେଣୁ p ଯୁଗ୍ମ; p = 2k ରଖିଲେ q² = 2k², q ମଧ୍ୟ ଯୁଗ୍ମ — ବିରୋଧାଭାସ।",
        keywords: ["ବିରୋଧାଭାସ", "ଯୁଗ୍ମ", "p/q"],
      },
      {
        q: "√3 କୁ ସଂଖ୍ୟାରେଖାରେ ଦର୍ଶାଇବାର ଉପାୟ ଲେଖ।",
        modelAnswer:
          "OA = 1 ନେଇ A ଠାରେ ଲମ୍ବ AB = √2; OB = √(1+2) = √3। O କୁ କେନ୍ଦ୍ର କରି OB ବ୍ୟାସାର୍ଦ୍ଧ ନେଇ ଚାପ ଅଙ୍କନ କଲେ ଏହା ସଂଖ୍ୟାରେଖାକୁ √3 ଠାରେ ଛେଦ କରିବ।",
        keywords: ["ପିଥାଗୋରାସ୍", "ଚାପ", "ଅଙ୍କନ"],
      },
    ],
  },

  "ssc-6-1:practice": {
    topicId: "ssc-6-1",
    difficulty: "practice",
    mcqs: [
      {
        q: "ସଡ଼କ ଦୁର୍ଘଟଣା ଦୃଷ୍ଟିରୁ ଭାରତ ପୃଥିବୀରେ କେଉଁ ସ୍ଥାନରେ?",
        options: ["ପ୍ରଥମ", "ଦ୍ୱିତୀୟ", "ତୃତୀୟ", "ଚତୁର୍ଥ"],
        correct: 0,
        explanation: "ଭାରତ ସଡ଼କ ଦୁର୍ଘଟଣାରେ ପ୍ରଥମ ସ୍ଥାନରେ ରହିଛି।",
      },
      {
        q: "ଭାରତରେ ପ୍ରତିଦିନ ପ୍ରାୟ କେତେ ଦୁର୍ଘଟଣା ଘଟୁଛି?",
        options: ["୧୦୦", "୫୦୦", "୧୨୦୦ ରୁ ଅଧିକ", "୨୦୦"],
        correct: 2,
        explanation: "୨୦୨୧ ତଥ୍ୟ ଅନୁସାରେ ୧୨୦୦ ରୁ ଊର୍ଦ୍ଧ୍ୱ।",
      },
      {
        q: "ସର୍ବାଧିକ ସଡ଼କ ଦୁର୍ଘଟଣା କେଉଁ ରାଜ୍ୟରେ ?",
        options: ["ଓଡ଼ିଶା", "ଉତ୍ତର ପ୍ରଦେଶ", "ତାମିଲନାଡ଼ୁ", "କେରଳ"],
        correct: 2,
        explanation: "ତାମିଲନାଡ଼ୁରେ ସର୍ବାଧିକ।",
      },
      {
        q: "ହେଲମେଟ୍ କେଉଁ ଯାନ ଚାଳକ ପାଇଁ ଆବଶ୍ୟକ?",
        options: ["କାର୍", "ମୋଟର ସାଇକେଲ୍", "ବସ୍", "ଟ୍ରକ୍"],
        correct: 1,
        explanation: "ମୋଟର ସାଇକେଲ୍/ସ୍କୁଟି ପାଇଁ ହେଲମେଟ୍ ନିତାନ୍ତ ଆବଶ୍ୟକ।",
      },
      {
        q: "ଦୁର୍ଘଟଣାର ମୁଖ୍ୟ କାରଣ ?",
        options: [
          "ଧିର ଗାଡ଼ି ଚାଳନା",
          "ଦୃତ ଓ ବେପରୁଆ ଚାଳନା",
          "ହେଲମେଟ୍ ବ୍ୟବହାର",
          "ସିଟ୍ ବେଲ୍ଟ୍",
        ],
        correct: 1,
        explanation: "ଦୃତ ଓ ବେପରୁଆ ଚାଳନା ସର୍ବାଧିକ କାରଣ।",
      },
    ],
    shortQs: [
      {
        q: "ସଡ଼କ ଦୁର୍ଘଟଣାର ତିନିଟି ମୁଖ୍ୟ କାରଣ ଲେଖ।",
        modelAnswer:
          "୧. ଦୃତ ଓ ବେପରୁଆ ଗାଡ଼ି ଚାଳନା। ୨. ନିଶାଗ୍ରସ୍ତ ଚାଳନା। ୩. ଯାନର ରକ୍ଷଣାବେକ୍ଷଣ ଅଭାବ।",
        keywords: ["ବେପରୁଆ", "ନିଶା", "ରକ୍ଷଣାବେକ୍ଷଣ"],
      },
      {
        q: "ସଡ଼କ ଦୁର୍ଘଟଣା ପ୍ରତିକାର ପାଇଁ ଦୁଇଟି ଉପାୟ ଲେଖ।",
        modelAnswer:
          "୧. ହେଲମେଟ୍ ଓ ସିଟ୍ ବେଲ୍ଟ୍ ବ୍ୟବହାର। ୨. ଯାତାୟାତ ନିୟମ ଓ ସଙ୍କେତ ମାନିବା।",
        keywords: ["ହେଲମେଟ୍", "ସିଟ୍ ବେଲ୍ଟ୍", "ନିୟମ"],
      },
    ],
  },
};

function fallbackQuiz(topic: DemoTopic, difficulty: "practice" | "master"): Quiz {
  const titleOr = topic.title.or;
  return {
    topicId: topic.id,
    difficulty,
    mcqs: [
      {
        q: `"${titleOr}" ଅଧ୍ୟାୟରୁ ମୁଖ୍ୟ ଧାରଣା କ'ଣ?`,
        options: [
          topic.objectives[0] ?? "ଧାରଣା ୧",
          topic.objectives[1] ?? "ଧାରଣା ୨",
          topic.objectives[2] ?? "ଧାରଣା ୩",
          "ଉପରୋକ୍ତ ସମସ୍ତ",
        ],
        correct: 3,
        explanation: "ସମସ୍ତ ଶିକ୍ଷଣ ଲକ୍ଷ୍ୟ ଏହି ଟପିକ୍ ର ଅଂଶ।",
      },
    ],
    shortQs: [
      {
        q: `"${titleOr}" ଟପିକ୍ ର ଶିକ୍ଷଣ ଲକ୍ଷ୍ୟ ଗୁଡ଼ିକ ଲେଖ।`,
        modelAnswer: topic.objectives.map((o, i) => `${i + 1}. ${o}`).join("\n"),
        keywords: topic.objectives.slice(0, 3),
      },
    ],
  };
}

export function getQuiz(
  topicId: string,
  difficulty: "practice" | "master" = "practice",
): Quiz {
  const key = `${topicId}:${difficulty}`;
  const existing = QUIZ_BANK[key];
  if (existing) return existing;

  const practiceKey = `${topicId}:practice`;
  const practice = QUIZ_BANK[practiceKey];
  if (practice && difficulty === "master") {
    // Use the practice bank but shuffle option order for master stage.
    return {
      ...practice,
      difficulty: "master",
      mcqs: practice.mcqs.map((m) => ({ ...m })),
    };
  }

  const topic = findTopic(topicId);
  if (!topic) {
    return {
      topicId,
      difficulty,
      mcqs: [],
      shortQs: [],
    };
  }
  return fallbackQuiz(topic, difficulty);
}

/** Score an attempt: returns percentage (0-100) and per-question correctness. */
export function scoreAttempt(
  quiz: Quiz,
  mcqAnswers: number[], // indices
  shortAnswers: string[],
): {
  mcqResults: Array<{ correct: boolean; expected: number; given: number }>;
  shortResults: Array<{ score: number; feedback: string }>; // score out of 5
  percent: number;
} {
  const mcqResults = quiz.mcqs.map((m, i) => ({
    correct: mcqAnswers[i] === m.correct,
    expected: m.correct,
    given: mcqAnswers[i] ?? -1,
  }));
  const mcqScore = mcqResults.filter((r) => r.correct).length;

  const shortResults = quiz.shortQs.map((s, i) => {
    const ans = (shortAnswers[i] ?? "").toLowerCase();
    const matched = s.keywords.filter((k) => ans.includes(k.toLowerCase()));
    const score = Math.min(5, Math.round((matched.length / Math.max(1, s.keywords.length)) * 5));
    return {
      score,
      feedback: matched.length
        ? `ଭଲ — "${matched.join('", "')}" ଶବ୍ଦ ମିଳିଛି।`
        : "ଉତ୍ତରରେ କୌଣସି ମୁଖ୍ୟ ଶବ୍ଦ ନାହିଁ। ଆଉ ଥରେ ଚେଷ୍ଟା କର।",
    };
  });
  const shortScore = shortResults.reduce((s, r) => s + r.score, 0);

  const mcqMax = quiz.mcqs.length;
  const shortMax = quiz.shortQs.length * 5;
  const total = mcqMax + shortMax;
  const obtained = mcqScore + shortScore;
  const percent = total === 0 ? 0 : Math.round((obtained / total) * 100);
  return { mcqResults, shortResults, percent };
}
