import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms governing use of Sikhya Sathi, the AI tutor for BSE Odisha Class 6–9 students.",
};

/**
 * Phase 15 — /legal/terms
 *
 * Launch-gating for UPI payment partners. Readable English; authoritative
 * version will live under docs/legal/terms.md after counsel review.
 */
export default function TermsPage() {
  const updated = "24 April 2026";
  return (
    <main className="container mx-auto max-w-3xl px-6 py-12 text-slate-700">
      <h1 className="text-3xl font-bold tracking-tight text-brand-900">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: {updated}</p>

      <section className="prose prose-slate mt-8 max-w-none">
        <h2>1. What Sikhya Sathi is</h2>
        <p>
          Sikhya Sathi is a digital learning service aligned to the Board of
          Secondary Education, Odisha (BSE) Class 6–9 syllabus. It provides
          AI-generated lessons, practice questions, and spaced-repetition
          review. Content is educational support, not a substitute for school.
        </p>

        <h2>2. Accounts</h2>
        <ul>
          <li>You are responsible for keeping your sign-in details safe.</li>
          <li>
            One account per learner. Sharing an account may result in
            suspension.
          </li>
          <li>
            If the learner is under 18, an adult (parent/guardian) must create
            and supervise the account.
          </li>
        </ul>

        <h2>3. Subscriptions and payment</h2>
        <ul>
          <li>
            Plans are listed on the{" "}
            <a href="/pricing">Pricing</a> page. Currency is Indian Rupees
            (INR).
          </li>
          <li>
            Payments are collected via UPI. After you pay, submit the UPI
            transaction reference (UTR) so we can verify and activate your
            plan.
          </li>
          <li>
            Subscriptions activate on verification and remain valid for the
            duration purchased. There is no auto-renewal.
          </li>
          <li>See our <a href="/legal/refund">Refund Policy</a> for refunds.</li>
        </ul>

        <h2>4. Acceptable use</h2>
        <ul>
          <li>No scraping, reselling, or redistributing generated content.</li>
          <li>No attempts to reverse-engineer the model prompts or infrastructure.</li>
          <li>No uploading of unlawful, hateful, or harassing content.</li>
        </ul>

        <h2>5. AI-generated content</h2>
        <p>
          Lessons and practice are generated by large language models grounded
          in the BSE textbook corpus. Errors are possible. If you find a
          mistake, please report it through the feedback form. Always cross-
          check critical facts with your textbook and teacher before an exam.
        </p>

        <h2>6. Intellectual property</h2>
        <p>
          The BSE textbooks cited in the app are © their respective rights-
          holders and used under fair-use educational review. Our product
          design, code, and generated explanations are © Sikhya Sathi.
        </p>

        <h2>7. Termination</h2>
        <p>
          You may delete your account at any time from Settings. We may
          suspend accounts that violate these terms. Paid plans that we
          terminate without fault will be refunded pro-rata.
        </p>

        <h2>8. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, Sikhya Sathi is not liable
          for indirect, incidental, or consequential damages arising from use
          of the service. Our aggregate liability is limited to the fees paid
          in the last 12 months.
        </p>

        <h2>9. Governing law</h2>
        <p>
          These terms are governed by the laws of India. Any disputes will be
          subject to the exclusive jurisdiction of the courts at Bhubaneswar,
          Odisha.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions:{" "}
          <a href="mailto:support@sikhyasathi.app">support@sikhyasathi.app</a>
        </p>
      </section>
    </main>
  );
}
